### ISSUE TITLE
s/betekend/betekent

### ISSUE THREAD

**Issue by nickygerritsen** [mlangerak-wolfpack/iets_met_address#1]
Typo!

**Comment by teunkoster** [comment]
sed: -e expression #1, char 19: unterminated `s' command

**Comment by nickygerritsen** [comment]
`s/s\/betekend\/betekent/s\/betekend\/betekent\//`

**Comment by mlangerak-wolfpack** [comment]
This question has been archived as "off topic and fuck this"
